package com.wallpaperteam.wallpaperhd.provider;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imageDBDaoConfig;

    private final ImageDBDao imageDBDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imageDBDaoConfig = daoConfigMap.get(ImageDBDao.class).clone();
        imageDBDaoConfig.initIdentityScope(type);

        imageDBDao = new ImageDBDao(imageDBDaoConfig, this);

        registerDao(ImageDB.class, imageDBDao);
    }
    
    public void clear() {
        imageDBDaoConfig.getIdentityScope().clear();
    }

    public ImageDBDao getImageDBDao() {
        return imageDBDao;
    }

}
