package com.wallpaperteam.wallpaperhd.provider;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "IMAGE_DB".
 */
public class ImageDB {

    private Long id;
    private String author;
    private Integer category;
    private String color;
    private Integer date;
    private Integer displayDate;
    private Integer featured;
    private String identifier;
    private Integer loved;
    private Integer width;
    private Integer height;
    private Long modifiedDate;
    private String platform;
    private String thumbnail;
    private String url;

    public ImageDB() {
    }

    public ImageDB(Long id) {
        this.id = id;
    }

    public ImageDB(Long id, String author, Integer category, String color, Integer date, Integer displayDate, Integer featured, String identifier, Integer loved, Integer width, Integer height, Long modifiedDate, String platform, String thumbnail, String url) {
        this.id = id;
        this.author = author;
        this.category = category;
        this.color = color;
        this.date = date;
        this.displayDate = displayDate;
        this.featured = featured;
        this.identifier = identifier;
        this.loved = loved;
        this.width = width;
        this.height = height;
        this.modifiedDate = modifiedDate;
        this.platform = platform;
        this.thumbnail = thumbnail;
        this.url = url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public Integer getCategory() {
        return category;
    }

    public void setCategory(Integer category) {
        this.category = category;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public Integer getDate() {
        return date;
    }

    public void setDate(Integer date) {
        this.date = date;
    }

    public Integer getDisplayDate() {
        return displayDate;
    }

    public void setDisplayDate(Integer displayDate) {
        this.displayDate = displayDate;
    }

    public Integer getFeatured() {
        return featured;
    }

    public void setFeatured(Integer featured) {
        this.featured = featured;
    }

    public String getIdentifier() {
        return identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public Integer getLoved() {
        return loved;
    }

    public void setLoved(Integer loved) {
        this.loved = loved;
    }

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Long getModifiedDate() {
        return modifiedDate;
    }

    public void setModifiedDate(Long modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    public String getPlatform() {
        return platform;
    }

    public void setPlatform(String platform) {
        this.platform = platform;
    }

    public String getThumbnail() {
        return thumbnail;
    }

    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
